from .common import *

from .dev import *

import os

TEST_ENV = os.getenv("TEST_ENV", "dev")


def to_absolute_path(path):
    return list(map(lambda p: os.path.abspath(p), path))


DEFAULT_IMAGELIST = to_absolute_path(DEFAULT_IMAGELIST)
PROFILE_IMAGELIST = to_absolute_path(PROFILE_IMAGELIST)
LARGE_IMAGELIST = to_absolute_path(LARGE_IMAGELIST)
PDF_FILELIST = to_absolute_path(PDF_FILELIST)

DEFAULT_IMAGELIST_ONE = DEFAULT_IMAGELIST[:1]
DEFAULT_IMAGELIST_TWO = DEFAULT_IMAGELIST[:2]
DEFAULT_IMAGELIST_THREE = DEFAULT_IMAGELIST[:3]
DEFAULT_IMAGELIST_FOUR = DEFAULT_IMAGELIST[:4]
PROFILE_IMAGE = PROFILE_IMAGELIST[:1]
LARGE_IMAGE = LARGE_IMAGELIST[:1]
PDF_FILE = PDF_FILELIST[:1]